# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.srcs/sources_1/bd/ofdm_tx/ip/ofdm_tx_pilot_0_0/ofdm_tx_pilot_0_0.xci
# IP: The module: 'ofdm_tx_pilot_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.srcs/sources_1/ip/pilot_ram/pilot_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pilot_ram || ORIG_REF_NAME==pilot_ram} -quiet] -quiet

# XDC: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.gen/sources_1/bd/ofdm_tx/ip/ofdm_tx_pilot_0_0/ofdm_tx_pilot_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ofdm_tx_pilot_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.srcs/sources_1/bd/ofdm_tx/ip/ofdm_tx_pilot_0_0/ofdm_tx_pilot_0_0.xci
# IP: The module: 'ofdm_tx_pilot_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.srcs/sources_1/ip/pilot_ram/pilot_ram.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pilot_ram || ORIG_REF_NAME==pilot_ram} -quiet] -quiet

# XDC: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.gen/sources_1/bd/ofdm_tx/ip/ofdm_tx_pilot_0_0/ofdm_tx_pilot_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ofdm_tx_pilot_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
