set_property IOSTANDARD LVCMOS33 [get_ports dacClk]
set_property IOSTANDARD LVCMOS33 [get_ports dacWrt]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dacData[13]}]
set_property PACKAGE_PIN E10 [get_ports dacClk]
set_property PACKAGE_PIN B11 [get_ports dacWrt]
set_property PACKAGE_PIN E11 [get_ports {dacData[0]}]
set_property PACKAGE_PIN C11 [get_ports {dacData[1]}]
set_property PACKAGE_PIN D10 [get_ports {dacData[2]}]
set_property PACKAGE_PIN C13 [get_ports {dacData[3]}]
set_property PACKAGE_PIN D9  [get_ports {dacData[4]}]
set_property PACKAGE_PIN A14 [get_ports {dacData[5]}]
set_property PACKAGE_PIN D11 [get_ports {dacData[6]}]
set_property PACKAGE_PIN D14 [get_ports {dacData[7]}]
set_property PACKAGE_PIN E12 [get_ports {dacData[8]}]
set_property PACKAGE_PIN B12 [get_ports {dacData[9]}]
set_property PACKAGE_PIN C12 [get_ports {dacData[10]}]
set_property PACKAGE_PIN C14 [get_ports {dacData[11]}]
set_property PACKAGE_PIN D13 [get_ports {dacData[12]}]
set_property PACKAGE_PIN B14 [get_ports {dacData[13]}]



