# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Desktop/tb/tb/tb.srcs/sources_1/ip/pilot_ram/pilot_ram.xci
# IP: The module: 'pilot_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/tb/tb/tb.gen/sources_1/ip/pilot_ram/pilot_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pilot_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Administrator/Desktop/tb/tb/tb.srcs/sources_1/ip/pilot_ram/pilot_ram.xci
# IP: The module: 'pilot_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/tb/tb/tb.gen/sources_1/ip/pilot_ram/pilot_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pilot_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
