# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.srcs/sources_1/ip/pll_clk/pll_clk.xci
# IP: The module: 'pll_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.gen/sources_1/ip/pll_clk/pll_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.gen/sources_1/ip/pll_clk/pll_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.gen/sources_1/ip/pll_clk/pll_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.srcs/sources_1/ip/pll_clk/pll_clk.xci
# IP: The module: 'pll_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.gen/sources_1/ip/pll_clk/pll_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.gen/sources_1/ip/pll_clk/pll_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.gen/sources_1/ip/pll_clk/pll_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
