@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 05 18:37:30 +0800 2024
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim test_TxTop_behav -key {Behavioral:sim_1:Functional:test_TxTop} -tclbatch test_TxTop.tcl -protoinst "protoinst_files/ofdm_tx.protoinst" -view E:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/test_TxTop_behav.wcfg -log simulate.log"
call xsim  test_TxTop_behav -key {Behavioral:sim_1:Functional:test_TxTop} -tclbatch test_TxTop.tcl -protoinst "protoinst_files/ofdm_tx.protoinst" -view E:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/test_TxTop_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
