# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ofdm_tx/ofdm_tx.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx || ORIG_REF_NAME==ofdm_tx} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_interleaver_2_0_0/ofdm_tx_interleaver_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_interleaver_2_0_0 || ORIG_REF_NAME==ofdm_tx_interleaver_2_0_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_tx_mcu_0_0/ofdm_tx_tx_mcu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_tx_mcu_0_0 || ORIG_REF_NAME==ofdm_tx_tx_mcu_0_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_interleaver_1_0_0/ofdm_tx_interleaver_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_interleaver_1_0_0 || ORIG_REF_NAME==ofdm_tx_interleaver_1_0_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_convenc_0_0/ofdm_tx_convenc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_convenc_0_0 || ORIG_REF_NAME==ofdm_tx_convenc_0_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_scramler_0_0/ofdm_tx_scramler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_scramler_0_0 || ORIG_REF_NAME==ofdm_tx_scramler_0_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_maping_0_0/ofdm_tx_maping_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_maping_0_0 || ORIG_REF_NAME==ofdm_tx_maping_0_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_puncture_0_0/ofdm_tx_puncture_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_puncture_0_0 || ORIG_REF_NAME==ofdm_tx_puncture_0_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_symbol_train_0_0/ofdm_tx_symbol_train_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_symbol_train_0_0 || ORIG_REF_NAME==ofdm_tx_symbol_train_0_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_pilot_0_0/ofdm_tx_pilot_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_pilot_0_0 || ORIG_REF_NAME==ofdm_tx_pilot_0_0} -quiet] -quiet

# IP: ip/pilot_ram/pilot_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pilot_ram || ORIG_REF_NAME==pilot_ram} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_dac_0_0/ofdm_tx_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_dac_0_0 || ORIG_REF_NAME==ofdm_tx_dac_0_0} -quiet] -quiet

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_ifft_0_0/ofdm_tx_ifft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_ifft_0_0 || ORIG_REF_NAME==ofdm_tx_ifft_0_0} -quiet] -quiet

# IP: ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: bd/ofdm_tx/ip/ofdm_tx_util_vector_logic_0_0/ofdm_tx_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_tx_util_vector_logic_0_0 || ORIG_REF_NAME==ofdm_tx_util_vector_logic_0_0} -quiet] -quiet

# XDC: e:/86152/FPGA/Verilog/file_management/UDP_OFDM/rtl/UDP_DDR_OFDM/src/OFDM/tb/tb/tb.gen/sources_1/bd/ofdm_tx/ofdm_tx_ooc.xdc
